Traceback (most recent call last):
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import plotly.express as px
import numpy as np

df = pd.read_excel("whc-sites-2023.xls")
df = df[df['Visited'].notna()]
max_bound = max(abs(min(df['latitude'])-max(df['latitude'])), abs(min(df['longitude'])-max(df['longitude']))) * 175
zoom = 11.5 - np.log(max_bound)
fig = px.scatter_mapbox(df, lat='latitude', lon='longitude', color='Visited',
                        hover_name='name_en', mapbox_style='carto-positron', zoom=zoom,
                        hover_data={
                            'latitude':False,
                            'longitude':False
                        })
fig.update_layout(showlegend=False, margin={'t':0,'l':0,'b':0,'r':0})
fig.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\pandas\compat\_optional.py:135[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    134[0m [38;5;28;01mtry[39;00m:
[1;32m--> 135[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[0;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\importlib\__init__.py:90[0m, in [0;36mimport_module[1;34m(name, package)[0m
[0;32m     89[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m---> 90[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [1;32m<frozen importlib._bootstrap>:1387[0m, in [0;36m_gcd_import[1;34m(name, package, level)[0m

File [1;32m<frozen importlib._bootstrap>:1360[0m, in [0;36m_find_and_load[1;34m(name, import_)[0m

File [1;32m<frozen importlib._bootstrap>:1324[0m, in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'xlrd'

During handling of the above exception, another exception occurred:

[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[1], line 5[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m----> 5[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mwhc-sites-2023.xls[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      6[0m df [38;5;241m=[39m df[df[[38;5;124m'[39m[38;5;124mVisited[39m[38;5;124m'[39m][38;5;241m.[39mnotna()]
[0;32m      7[0m max_bound [38;5;241m=[39m [38;5;28mmax[39m([38;5;28mabs[39m([38;5;28mmin[39m(df[[38;5;124m'[39m[38;5;124mlatitude[39m[38;5;124m'[39m])[38;5;241m-[39m[38;5;28mmax[39m(df[[38;5;124m'[39m[38;5;124mlatitude[39m[38;5;124m'[39m])), [38;5;28mabs[39m([38;5;28mmin[39m(df[[38;5;124m'[39m[38;5;124mlongitude[39m[38;5;124m'[39m])[38;5;241m-[39m[38;5;28mmax[39m(df[[38;5;124m'[39m[38;5;124mlongitude[39m[38;5;124m'[39m]))) [38;5;241m*[39m [38;5;241m175[39m

File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\pandas\io\excel\_base.py:495[0m, in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)[0m
[0;32m    493[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[0;32m    494[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 495[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m
[0;32m    496[0m [43m        [49m[43mio[49m[43m,[49m
[0;32m    497[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[0;32m    498[0m [43m        [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m,[49m
[0;32m    499[0m [43m        [49m[43mengine_kwargs[49m[38;5;241;43m=[39;49m[43mengine_kwargs[49m[43m,[49m
[0;32m    500[0m [43m    [49m[43m)[49m
[0;32m    501[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[0;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    503[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[0;32m    504[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[0;32m    505[0m     )

File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\pandas\io\excel\_base.py:1567[0m, in [0;36mExcelFile.__init__[1;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)[0m
[0;32m   1564[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[0;32m   1565[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[1;32m-> 1567[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engines[49m[43m[[49m[43mengine[49m[43m][49m[43m([49m
[0;32m   1568[0m [43m    [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_io[49m[43m,[49m
[0;32m   1569[0m [43m    [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[0;32m   1570[0m [43m    [49m[43mengine_kwargs[49m[38;5;241;43m=[39;49m[43mengine_kwargs[49m[43m,[49m
[0;32m   1571[0m [43m[49m[43m)[49m

File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\pandas\io\excel\_xlrd.py:45[0m, in [0;36mXlrdReader.__init__[1;34m(self, filepath_or_buffer, storage_options, engine_kwargs)[0m
[0;32m     33[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[0;32m     34[0m [38;5;124;03mReader using xlrd engine.[39;00m
[0;32m     35[0m 
[1;32m   (...)[0m
[0;32m     42[0m [38;5;124;03m    Arbitrary keyword arguments passed to excel engine.[39;00m
[0;32m     43[0m [38;5;124;03m"""[39;00m
[0;32m     44[0m err_msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mInstall xlrd >= 2.0.1 for xls Excel support[39m[38;5;124m"[39m
[1;32m---> 45[0m [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mxlrd[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mextra[49m[38;5;241;43m=[39;49m[43merr_msg[49m[43m)[49m
[0;32m     46[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(
[0;32m     47[0m     filepath_or_buffer,
[0;32m     48[0m     storage_options[38;5;241m=[39mstorage_options,
[0;32m     49[0m     engine_kwargs[38;5;241m=[39mengine_kwargs,
[0;32m     50[0m )

File [1;32m~\AppData\Local\miniconda3\envs\jupyterbook\Lib\site-packages\pandas\compat\_optional.py:138[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    136[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m    137[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[1;32m--> 138[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m    139[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[0;32m    141[0m [38;5;66;03m# Handle submodules: if we have submodule, grab parent module from sys.modules[39;00m

[1;31mImportError[0m: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

